apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apollo-ingress
  namespace: apollo-dash0-demo
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: router.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apollo-router
            port:
              number: 4000
  - host: website.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: willful-waste-website
            port:
              number: 8080
