apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: apollo-dash0-demo

resources:
  - postgres-cluster.yaml
  - postgres-exporter.yaml
  - dash0-monitoring.yaml
  - website.yaml
  # - website-bot.yaml  # Website bot is kept in the codebase but not deployed
  - ingress.yaml
  - subgraphs/accounts.yaml
  - subgraphs/inventory.yaml
  - subgraphs/products.yaml
  - subgraphs/reviews.yaml